image: docker:latest

stages:
  - build
  #- deploy

services:
  - docker:dind

variables:
  #  GIT_STRATEGY: clone
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_DRIVER: overlay2
  SERVICE_NAME: geoexpress_geonode

cache:
  key: "$CI_BUILD_REF_SLUG"
  
before_script:
  - echo '${CI_COMMIT_BRANCH}'
  - echo 'Environment for branch= ${CI_BUILD_REF_NAME} - commit= ${CI_BUILD_REF}'
  - env | grep "^CI_"
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - docker -v
  - docker compose version

build:
  stage: build
  script:
    - docker build -t $CI_BUILD_REF_SLUG-local --file Dockerfile .
    - docker tag $CI_BUILD_REF_SLUG-local $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web"'