# coding: utf-8

"""
    GeoServer ACL

    GeoServer Access Control List API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from geonode.geoserver.acl.gsauth_client.configuration import Configuration


class AdminRuleFilter(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'instance': 'TextFilter',
        'grant_type': 'AdminGrantType',
        'user': 'TextFilter',
        'roles': 'SetFilter',
        'workspace': 'TextFilter',
        'source_address': 'AddressRangeFilter'
    }

    attribute_map = {
        'instance': 'instance',
        'grant_type': 'grantType',
        'user': 'user',
        'roles': 'roles',
        'workspace': 'workspace',
        'source_address': 'sourceAddress'
    }

    def __init__(self, instance=None, grant_type=None, user=None, roles=None, workspace=None, source_address=None, local_vars_configuration=None):  # noqa: E501
        """AdminRuleFilter - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._instance = None
        self._grant_type = None
        self._user = None
        self._roles = None
        self._workspace = None
        self._source_address = None
        self.discriminator = None

        self.instance = instance
        self.grant_type = grant_type
        self.user = user
        self.roles = roles
        self.workspace = workspace
        self.source_address = source_address

    @property
    def instance(self):
        """Gets the instance of this AdminRuleFilter.  # noqa: E501


        :return: The instance of this AdminRuleFilter.  # noqa: E501
        :rtype: TextFilter
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this AdminRuleFilter.


        :param instance: The instance of this AdminRuleFilter.  # noqa: E501
        :type instance: TextFilter
        """

        self._instance = instance

    @property
    def grant_type(self):
        """Gets the grant_type of this AdminRuleFilter.  # noqa: E501


        :return: The grant_type of this AdminRuleFilter.  # noqa: E501
        :rtype: AdminGrantType
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this AdminRuleFilter.


        :param grant_type: The grant_type of this AdminRuleFilter.  # noqa: E501
        :type grant_type: AdminGrantType
        """

        self._grant_type = grant_type

    @property
    def user(self):
        """Gets the user of this AdminRuleFilter.  # noqa: E501


        :return: The user of this AdminRuleFilter.  # noqa: E501
        :rtype: TextFilter
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AdminRuleFilter.


        :param user: The user of this AdminRuleFilter.  # noqa: E501
        :type user: TextFilter
        """

        self._user = user

    @property
    def roles(self):
        """Gets the roles of this AdminRuleFilter.  # noqa: E501


        :return: The roles of this AdminRuleFilter.  # noqa: E501
        :rtype: SetFilter
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this AdminRuleFilter.


        :param roles: The roles of this AdminRuleFilter.  # noqa: E501
        :type roles: SetFilter
        """

        self._roles = roles

    @property
    def workspace(self):
        """Gets the workspace of this AdminRuleFilter.  # noqa: E501


        :return: The workspace of this AdminRuleFilter.  # noqa: E501
        :rtype: TextFilter
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this AdminRuleFilter.


        :param workspace: The workspace of this AdminRuleFilter.  # noqa: E501
        :type workspace: TextFilter
        """

        self._workspace = workspace

    @property
    def source_address(self):
        """Gets the source_address of this AdminRuleFilter.  # noqa: E501


        :return: The source_address of this AdminRuleFilter.  # noqa: E501
        :rtype: AddressRangeFilter
        """
        return self._source_address

    @source_address.setter
    def source_address(self, source_address):
        """Sets the source_address of this AdminRuleFilter.


        :param source_address: The source_address of this AdminRuleFilter.  # noqa: E501
        :type source_address: AddressRangeFilter
        """

        self._source_address = source_address

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminRuleFilter):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdminRuleFilter):
            return True

        return self.to_dict() != other.to_dict()
