# coding: utf-8

"""
    GeoServer ACL

    GeoServer Access Control List API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from geonode.geoserver.acl.gsauth_client.configuration import Configuration


class RuleLimits(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'allowed_area': 'Geom',
        'spatial_filter_type': 'SpatialFilterType',
        'catalog_mode': 'CatalogMode'
    }

    attribute_map = {
        'allowed_area': 'allowedArea',
        'spatial_filter_type': 'spatialFilterType',
        'catalog_mode': 'catalogMode'
    }

    def __init__(self, allowed_area=None, spatial_filter_type=None, catalog_mode=None, local_vars_configuration=None):  # noqa: E501
        """RuleLimits - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._allowed_area = None
        self._spatial_filter_type = None
        self._catalog_mode = None
        self.discriminator = None

        if allowed_area is not None:
            self.allowed_area = allowed_area
        self.spatial_filter_type = spatial_filter_type
        self.catalog_mode = catalog_mode

    @property
    def allowed_area(self):
        """Gets the allowed_area of this RuleLimits.  # noqa: E501


        :return: The allowed_area of this RuleLimits.  # noqa: E501
        :rtype: Geom
        """
        return self._allowed_area

    @allowed_area.setter
    def allowed_area(self, allowed_area):
        """Sets the allowed_area of this RuleLimits.


        :param allowed_area: The allowed_area of this RuleLimits.  # noqa: E501
        :type allowed_area: Geom
        """

        self._allowed_area = allowed_area

    @property
    def spatial_filter_type(self):
        """Gets the spatial_filter_type of this RuleLimits.  # noqa: E501


        :return: The spatial_filter_type of this RuleLimits.  # noqa: E501
        :rtype: SpatialFilterType
        """
        return self._spatial_filter_type

    @spatial_filter_type.setter
    def spatial_filter_type(self, spatial_filter_type):
        """Sets the spatial_filter_type of this RuleLimits.


        :param spatial_filter_type: The spatial_filter_type of this RuleLimits.  # noqa: E501
        :type spatial_filter_type: SpatialFilterType
        """

        self._spatial_filter_type = spatial_filter_type

    @property
    def catalog_mode(self):
        """Gets the catalog_mode of this RuleLimits.  # noqa: E501


        :return: The catalog_mode of this RuleLimits.  # noqa: E501
        :rtype: CatalogMode
        """
        return self._catalog_mode

    @catalog_mode.setter
    def catalog_mode(self, catalog_mode):
        """Sets the catalog_mode of this RuleLimits.


        :param catalog_mode: The catalog_mode of this RuleLimits.  # noqa: E501
        :type catalog_mode: CatalogMode
        """

        self._catalog_mode = catalog_mode

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuleLimits):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RuleLimits):
            return True

        return self.to_dict() != other.to_dict()
